# -*- coding: utf-8 -*-
"""stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13rGRGg0L7myUIkOu9x2C3OxV1k5Y7U-J
"""

import numpy as np
import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt
from pandas.plotting import table
import six
def render_mpl_table(data, col_width=3.0, row_height=0.625, font_size=14,
                     header_color='#40466e', row_colors=['#f1f1f2', 'w'], edge_color='w',
                     bbox=[0, 0, 1, 1], header_columns=0,
                     ax=None, **kwargs):
    if ax is None:
        size = (np.array(data.shape[::-1]) + np.array([0, 1])) * np.array([col_width, row_height])
        fig, ax = plt.subplots(figsize=size)
        ax.axis('off')

    mpl_table = ax.table(cellText=data.values, bbox=bbox, colLabels=data.columns, **kwargs)

    mpl_table.auto_set_font_size(False)
    mpl_table.set_fontsize(font_size)

    for k, cell in  six.iteritems(mpl_table._cells):
        cell.set_edgecolor(edge_color)
        if k[0] == 0 or k[1] < header_columns:
            cell.set_text_props(weight='bold', color='w')
            cell.set_facecolor(header_color)
        else:
            cell.set_facecolor(row_colors[k[0]%len(row_colors) ])
    return ax
files.upload()
dataset = pd.read_csv('stats.csv')
rng = np.random.randint(50, size=10)
num_times = 0
num_times_in_inst = 0
dataframe = np.zeros(50, dtype=int)
for i in range(0, 50):
  rng = np.random.randint(100, size=10)
  for x in range(0, 10):
    if rng[x] == 4 or rng[x] == 3 or rng[x] == 10 or rng[x] == 1 or rng[x] == 2 or rng[x] == 5:
      num_times_in_inst += 1
  dataset.at[num_times_in_inst, 'frequency'] += 1
  dataframe[i] = num_times_in_inst
  num_times_in_inst = 0
  
dataframe = dataframe.reshape(-1, 1)
render_mpl_table(dataset, col_width=6.0)
plt.show()
plt.hist(dataframe, bins=10, range=(0, 10))
plt.xlabel('Number of Universal Donors in a group of 10')
plt.ylabel('Frequency')
plt.show()